/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view;

/**
 *
 * @author Tom
 */
public class CategoryList extends javax.swing.JPanel {
	MenuBar fen;

	/**
	 * Creates new form CategoryList
	 * @param fen
	 */
	public CategoryList(MenuBar fen) {
		super();
		initComponents();
		this.fen=fen;	 
	}


	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabelAuthorName1 = new javax.swing.JLabel();
    jTextFieldCategory = new javax.swing.JTextField();
    jButtonCreateAthor = new javax.swing.JButton();
    jLabelAuthorName = new javax.swing.JLabel();
    jButtonSearchAthor = new javax.swing.JButton();
    jTextFieldCategoryName = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTableAuthor = new javax.swing.JTable();
    JLabelCreateAuthor = new javax.swing.JLabel();
    JLabelCreateAuthor1 = new javax.swing.JLabel();

    jLabelAuthorName1.setText("jLabelCategory");

    jTextFieldCategory.setText("jTextFieldCategory");
    jTextFieldCategory.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldCategoryActionPerformed(evt);
      }
    });

    jButtonCreateAthor.setText("jButtonCreateCategory");
    jButtonCreateAthor.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonCreateAthorActionPerformed(evt);
      }
    });

    jLabelAuthorName.setText("jLabelCategoryName");

    jButtonSearchAthor.setText("jButtonSearchCategory");
    jButtonSearchAthor.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonSearchAthorActionPerformed(evt);
      }
    });

    jTextFieldCategoryName.setText("jTextFieldCategoryName");
    jTextFieldCategoryName.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldCategoryNameActionPerformed(evt);
      }
    });

    jTableAuthor.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(jTableAuthor);

    JLabelCreateAuthor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    JLabelCreateAuthor.setText("JLabelCreateCategory");

    JLabelCreateAuthor1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    JLabelCreateAuthor1.setText("JLabelSearchCategory");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabelAuthorName)
          .addComponent(jTextFieldCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelAuthorName1)
          .addComponent(jTextFieldCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(JLabelCreateAuthor1)
          .addComponent(JLabelCreateAuthor))
        .addGap(168, 168, 168)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButtonSearchAthor)
          .addComponent(jButtonCreateAthor))
        .addContainerGap(51, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addComponent(JLabelCreateAuthor)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelAuthorName)
          .addComponent(jButtonCreateAthor))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTextFieldCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(30, 30, 30)
        .addComponent(JLabelCreateAuthor1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelAuthorName1)
          .addComponent(jButtonSearchAthor))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTextFieldCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jTextFieldCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCategoryActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextFieldCategoryActionPerformed

  private void jButtonCreateAthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateAthorActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButtonCreateAthorActionPerformed

  private void jButtonSearchAthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchAthorActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButtonSearchAthorActionPerformed

  private void jTextFieldCategoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCategoryNameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextFieldCategoryNameActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel JLabelCreateAuthor;
  private javax.swing.JLabel JLabelCreateAuthor1;
  private javax.swing.JButton jButtonCreateAthor;
  private javax.swing.JButton jButtonSearchAthor;
  private javax.swing.JLabel jLabelAuthorName;
  private javax.swing.JLabel jLabelAuthorName1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTableAuthor;
  private javax.swing.JTextField jTextFieldCategory;
  private javax.swing.JTextField jTextFieldCategoryName;
  // End of variables declaration//GEN-END:variables
}
