/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view;

import java.util.ArrayList;

import javax.swing.JOptionPane;

import app.App;
import app.database.Database;
import app.entity.UserEntity;
import app.model.UserModel;

/**
 *
 * @author Tom
 */
public class Login extends javax.swing.JPanel {
	MenuBar fen;

	/**
	 * Creates new form Login
	 * @param fen
	 */
	public Login(MenuBar fen) {
		super();
		initComponents();
		this.fen=fen;	 
	}


	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabelLogin = new javax.swing.JLabel();
    jTextFieldLogin = new javax.swing.JTextField(20);
    jLabelPass = new javax.swing.JLabel();
    jTextFieldPass = new javax.swing.JTextField(20);
    jButtonValidate = new javax.swing.JButton();
    jButtonCancel = new javax.swing.JButton();

    jLabelLogin.setText("Login");

    jTextFieldLogin.setText("");
    jTextFieldLogin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldLoginActionPerformed(evt);
      }
    });

    jLabelPass.setText("Password");

    jTextFieldPass.setText("");
    jTextFieldPass.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldPassActionPerformed(evt);
      }
    });

    Database db = App.getDb();
    UserModel model = new UserModel(db);
    
    jButtonValidate.setText("Valider");
    jButtonValidate.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonValidateActionPerformed(evt);
        
        String login = null, password = null, name = null, firstname = null;
        ArrayList<UserEntity> user = new ArrayList();

        if(evt.getActionCommand().contains("Valider")){
        	login = jTextFieldLogin.getText().trim();
        	password = jTextFieldPass.getText().trim();
        	
        	
        	if(login.equalsIgnoreCase("") && password.equalsIgnoreCase("") ){
        		JOptionPane.showMessageDialog(fen,"Veuillez remplir les champs demandés");
        	}
        	else if(login.length() >= 1 && password.length() >= 1){
        		user = model.checkLog(login, password);
        		
        		if(user.size() == 0){
					JOptionPane.showMessageDialog(fen,"Aucun utilisateur correspondant");
				}

				for (int i = 0; i < user.size(); i++){
					 name = user.get(i).getName();
					firstname = user.get(i).getFirstname();
				}
				
					fen.change(4);
				
        	}
        	else if(login.equalsIgnoreCase("") || password.equalsIgnoreCase("")){
        		JOptionPane.showMessageDialog(fen,"Veuillez renseigner correctement vos identifiants");
        	}
        }
      }
    });
    
    jButtonCancel.setText("Annuler");
    jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonCancelActionPerformed(evt);
        if(evt.getActionCommand().contains("Annuler")){
        	fen.change(4);
        }
        
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(159, 159, 159)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabelPass)
              .addComponent(jTextFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabelLogin)
              .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(layout.createSequentialGroup()
            .addGap(73, 73, 73)
            .addComponent(jButtonValidate)
            .addGap(37, 37, 37)
            .addComponent(jButtonCancel)))
        .addContainerGap(86, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(52, 52, 52)
        .addComponent(jLabelLogin)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabelPass)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTextFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(42, 42, 42)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButtonValidate)
          .addComponent(jButtonCancel))
        .addContainerGap(85, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jTextFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoginActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextFieldLoginActionPerformed

  private void jTextFieldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPassActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextFieldPassActionPerformed

  private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButtonCancelActionPerformed

  private void jButtonValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidateActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButtonValidateActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonCancel;
  private javax.swing.JButton jButtonValidate;
  private javax.swing.JLabel jLabelLogin;
  private javax.swing.JLabel jLabelPass;
  private javax.swing.JTextField jTextFieldLogin;
  private javax.swing.JTextField jTextFieldPass;
  // End of variables declaration//GEN-END:variables
}
