/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view;


/**
 *
 * @author Tom
 */
public class MenuBar extends javax.swing.JFrame {

	AuthorCreate authorCreate = new AuthorCreate(this);
	BookCreate bookCreate = new BookCreate(this);
	BookDetail bookDetail = new BookDetail(this);
	BookList bookList = new BookList(this);
	CategoryList categoryList = new CategoryList(this);
	Login login = new Login(this);
	LoginCreate loginCreate = new LoginCreate(this);
	UserCreate userCreate = new UserCreate(this);
	UserList userList = new UserList(this);
	
	

	/**
	 * Creates new form listeLivre
	 */
	public MenuBar() {
		initComponents();
		//this.setContentPane(p);

	}
/**
 * Transitions entre les différents panels
 * @param i 
 */
	public void change(int i) {
		switch (i) {
			case 1:
				this.setContentPane(authorCreate);
				System.out.println("case 1 done : authorCreate");
				break;
			case 2:
				this.setContentPane(bookCreate);
				System.out.println("case 2 done : bookCreate");
				break;
			case 3:
				this.setContentPane(bookDetail);
				System.out.println("case 3 done : bookDetail");
				break;
			case 4:
				this.setContentPane(bookList);
				System.out.println("case 4 done : bookList");
				break;
			case 5:
				this.setContentPane(categoryList);
				System.out.println("case 5 done : categoryList");
				break;
			case 6:
				this.setContentPane(login);
				System.out.println("case 6 done : login");
				break;
			case 7:
				this.setContentPane(loginCreate);
				System.out.println("case 7 done : loginCreate");
				break;
			case 8:
				this.setContentPane(userCreate);
				System.out.println("case 8 done : userCreate");
				break;
			case 9:
				this.setContentPane(userList);
				System.out.println("case 9 done : userList");
				break;
			default:
				System.out.println("ERREUR");
				break;

		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jMenuItem1 = new javax.swing.JMenuItem();
    leJPanel = new javax.swing.JPanel();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu6 = new javax.swing.JMenu();
    jMenu2 = new javax.swing.JMenu();
    jMenu8 = new javax.swing.JMenu();
    jMenu9 = new javax.swing.JMenu();
    jMenu10 = new javax.swing.JMenu();
    jMenu4 = new javax.swing.JMenu();
    jMenu5 = new javax.swing.JMenu();
    jMenuItem2 = new javax.swing.JMenuItem();
    jMenu11 = new javax.swing.JMenu();
    jMenu13 = new javax.swing.JMenu();
    jMenu17 = new javax.swing.JMenu();

    jMenuItem1.setText("jMenuItem1");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setAutoRequestFocus(false);

    javax.swing.GroupLayout leJPanelLayout = new javax.swing.GroupLayout(leJPanel);
    leJPanel.setLayout(leJPanelLayout);
    leJPanelLayout.setHorizontalGroup(
      leJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 731, Short.MAX_VALUE)
    );
    leJPanelLayout.setVerticalGroup(
      leJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 445, Short.MAX_VALUE)
    );

    jMenu6.setText("Recherche");
    jMenuBar1.add(jMenu6);

    jMenu2.setText("Emprunts");
    jMenuBar1.add(jMenu2);

    jMenu8.setText("Connexion");

    jMenu9.setText("S'inscrire");
    jMenu8.add(jMenu9);

    jMenu10.setText("Se connecter");
    jMenu8.add(jMenu10);

    jMenuBar1.add(jMenu8);

    jMenu4.setText("Administration");

    jMenu5.setText("Livre");

    jMenuItem2.setText("Lister");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem2ActionPerformed(evt);
      }
    });
    jMenu5.add(jMenuItem2);

    jMenu4.add(jMenu5);

    jMenu11.setText("Autheur");
    jMenu4.add(jMenu11);

    jMenu13.setText("Catégorie");
    jMenu4.add(jMenu13);

    jMenu17.setText("Utilisateur");
    jMenu4.add(jMenu17);

    jMenuBar1.add(jMenu4);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(leJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(leJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jMenuItem2ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				MenuBar menuB = new MenuBar();
				menuB.setVisible(true);
				menuB.change(2);
			}
		});

	}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenu jMenu10;
  private javax.swing.JMenu jMenu11;
  private javax.swing.JMenu jMenu13;
  private javax.swing.JMenu jMenu17;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenu jMenu4;
  private javax.swing.JMenu jMenu5;
  private javax.swing.JMenu jMenu6;
  private javax.swing.JMenu jMenu8;
  private javax.swing.JMenu jMenu9;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JPanel leJPanel;
  // End of variables declaration//GEN-END:variables

}
