/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view;


/**
 *
 * @author Tom
 */
public class MenuBar extends javax.swing.JFrame {

	AuthorCreate authorCreate = new AuthorCreate(this);
	BookCreate bookCreate = new BookCreate(this);
	BookDetail bookDetail = new BookDetail(this);
	BookList bookList = new BookList(this);
	CategoryList categoryList = new CategoryList(this);
	Login login = new Login(this);
	LoginCreate loginCreate = new LoginCreate(this);
	UserCreate userCreate = new UserCreate(this);
	UserList userList = new UserList(this);
	
	

	/**
	 * Creates new form listeLivre
	 */
	public MenuBar() {
		initComponents();
		//this.setContentPane(p);

	}
/**
 * Transitions entre les différents panels
 * @param i 
 */
	public void change(int i) {
		switch (i) {
			case 1:
				this.setContentPane(authorCreate);
				System.out.println("case 1 done : authorCreate");
				break;
			case 2:
				this.setContentPane(bookCreate);
				System.out.println("case 2 done : bookCreate");
				break;
			case 3:
				this.setContentPane(bookDetail);
				System.out.println("case 3 done : bookDetail");
				break;
			case 4:
				this.setContentPane(bookList);
				System.out.println("case 4 done : bookList");
				break;
			case 5:
				this.setContentPane(categoryList);
				System.out.println("case 5 done : categoryList");
				break;
			case 6:
				this.setContentPane(login);
				System.out.println("case 6 done : login");
				break;
			case 7:
				this.setContentPane(loginCreate);
				System.out.println("case 7 done : loginCreate");
				break;
			case 8:
				this.setContentPane(userCreate);
				System.out.println("case 8 done : userCreate");
				break;
			case 9:
				this.setContentPane(userList);
				System.out.println("case 9 done : userList");
				break;
			default:
				System.out.println("ERREUR");
				break;

		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jMenuItem1 = new javax.swing.JMenuItem();
    leJPanel = new javax.swing.JPanel();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenuSearch = new javax.swing.JMenu();
    jMenuLoan = new javax.swing.JMenu();
    jMenuConnection = new javax.swing.JMenu();
    jMenuAdministration = new javax.swing.JMenu();
    jMenuBook = new javax.swing.JMenu();
    jMenuBookList = new javax.swing.JMenuItem();
    jMenuBookCreate = new javax.swing.JMenuItem();
    jMenuUser = new javax.swing.JMenu();
    jMenuUserList = new javax.swing.JMenuItem();
    jMenuUserCreate = new javax.swing.JMenuItem();
    jMenuAuthor = new javax.swing.JMenuItem();
    jMenuCategory = new javax.swing.JMenuItem();

    jMenuItem1.setText("jMenuItem1");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setAutoRequestFocus(false);

    javax.swing.GroupLayout leJPanelLayout = new javax.swing.GroupLayout(leJPanel);
    leJPanel.setLayout(leJPanelLayout);
    leJPanelLayout.setHorizontalGroup(
      leJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 731, Short.MAX_VALUE)
    );
    leJPanelLayout.setVerticalGroup(
      leJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 445, Short.MAX_VALUE)
    );

    jMenuSearch.setText("Recherche");
    jMenuBar1.add(jMenuSearch);

    jMenuLoan.setText("Emprunt");
    jMenuBar1.add(jMenuLoan);

    jMenuConnection.setText("Connexion");
    jMenuBar1.add(jMenuConnection);

    jMenuAdministration.setText("Administration");

    jMenuBook.setText("Livre");

    jMenuBookList.setText("Lister");
    jMenuBookList.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuBookListActionPerformed(evt);
      }
    });
    jMenuBook.add(jMenuBookList);

    jMenuBookCreate.setText("Creer");
    jMenuBookCreate.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuBookCreateActionPerformed(evt);
      }
    });
    jMenuBook.add(jMenuBookCreate);

    jMenuAdministration.add(jMenuBook);

    jMenuUser.setText("Utilisateur");

    jMenuUserList.setText("Lister");
    jMenuUser.add(jMenuUserList);

    jMenuUserCreate.setText("Creer");
    jMenuUser.add(jMenuUserCreate);

    jMenuAdministration.add(jMenuUser);

    jMenuAuthor.setText("Auteur");
    jMenuAdministration.add(jMenuAuthor);

    jMenuCategory.setText("Categorie");
    jMenuAdministration.add(jMenuCategory);

    jMenuBar1.add(jMenuAdministration);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(leJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(leJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jMenuBookListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBookListActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jMenuBookListActionPerformed

  private void jMenuBookCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBookCreateActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jMenuBookCreateActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				MenuBar menuB = new MenuBar();
				menuB.setVisible(true);
				menuB.change(2);
			}
		});

	}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenu jMenuAdministration;
  private javax.swing.JMenuItem jMenuAuthor;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenu jMenuBook;
  private javax.swing.JMenuItem jMenuBookCreate;
  private javax.swing.JMenuItem jMenuBookList;
  private javax.swing.JMenuItem jMenuCategory;
  private javax.swing.JMenu jMenuConnection;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenu jMenuLoan;
  private javax.swing.JMenu jMenuSearch;
  private javax.swing.JMenu jMenuUser;
  private javax.swing.JMenuItem jMenuUserCreate;
  private javax.swing.JMenuItem jMenuUserList;
  private javax.swing.JPanel leJPanel;
  // End of variables declaration//GEN-END:variables

}
